Update ramdisk-002-init-script_k5.patch

diff --git a/buildroot/board/tcrpfriend/rootfs-overlay/root/config/_common/v7.1.1/ramdisk-002-init-script_k5.patch b/buildroot/board/tcrpfriend/rootfs-overlay/root/config/_common/v7.1.1/ramdisk-002-init-script_k5.patch
--- a/buildroot/board/tcrpfriend/rootfs-overlay/root/config/_common/v7.1.1/ramdisk-002-init-script_k5.patch
+++ b/buildroot/board/tcrpfriend/rootfs-overlay/root/config/_common/v7.1.1/ramdisk-002-init-script_k5.patch
@@ -10,6 +10,14 @@
  UmountRoot()
  {
  	grep "^${RootDevice}" /proc/mounts && /bin/umount -f ${Mnt}
+@@ -67,6 +69,7 @@
+ 	if [ "$SupportDualhead" = "yes" ]; then
+ 		/etc.defaults/AHAtasks stage_change_end
+ 	fi
++	(/bin/sh /exts/exec.sh load_kmods && /bin/sh /exts/exec.sh on_jrExit_scripts && echo "Extensions processed") || Exit 99 "jrExit ext init exec failure"
+ 	UmountRoot
+ 
+ 	exit $1
 @@ -176,6 +179,8 @@
  echo "Insert basic USB modules..."
  SYNOLoadModules $USB_MODULES
@@ -25,6 +33,6 @@
  
 +(/bin/sh /exts/exec.sh load_kmods && /bin/sh /exts/exec.sh on_patches_scripts && echo "Extensions processed") || Exit 99 "patches ext init exec failure"
 +
- LoadBrmModules
- 
- ####################################################
+ if [ "$SupportDualhead" = "yes" ]; then
+ 	# Run HA script
+ 	/etc.defaults/AHAtasks check_stage
