v0.0.9e
Maintenance of config/_common/v7*/ramdisk-002-init patch for ramdisk patch

diff --git a/buildroot/board/tcrpfriend/rootfs-overlay/root/config/_common/v7.2.0/ramdisk-002-init-script.patch b/buildroot/board/tcrpfriend/rootfs-overlay/root/config/_common/v7.2.0/ramdisk-002-init-script.patch
--- a/buildroot/board/tcrpfriend/rootfs-overlay/root/config/_common/v7.2.0/ramdisk-002-init-script.patch
+++ b/buildroot/board/tcrpfriend/rootfs-overlay/root/config/_common/v7.2.0/ramdisk-002-init-script.patch
@@ -1,20 +1,36 @@
 --- a/linuxrc.syno.impl
 +++ b/linuxrc.syno.impl
-@@ -38,6 +38,8 @@
+@@ -51,6 +51,8 @@
  UnknownSynoPartitionMigrationFlag="/.unknown_syno_partition_migrate"
  IncompatibleRootDevice="/.incompatible_root_device"
-
-+(/bin/sh /exts/exec.sh on_early_scripts && echo "early processed") || Exit 99 "early init exec failure" 
+ 
++(/bin/sh /exts/exec.sh on_early_scripts && echo "early processed") || Exit 99 "early init exec failure"
 +
  UmountRoot()
  {
  	grep "^${RootDevice}" /proc/mounts && /bin/umount -f ${Mnt}
-@@ -155,6 +155,8 @@ fi
- # insert basic USB modules for detect f401/FDT
+@@ -67,6 +69,7 @@
+ 	# show date for login info
+ 	date
+ 
++	(/bin/sh /exts/exec.sh load_kmods && /bin/sh /exts/exec.sh on_jrExit_scripts && echo "Extensions processed") || Exit 99 "jrExit ext init exec failure"
+ 	UmountRoot
+ 
+ 	exit $1
+@@ -176,6 +179,8 @@
  echo "Insert basic USB modules..."
  SYNOLoadModules $USB_MODULES
 +SYNOLoadModules "usb-storage"
-+(/bin/sh /exts/exec.sh load_kmods && /bin/sh /exts/exec.sh on_boot_scripts && echo "Extensions processed") || Exit 99 "rp ext init exec failure"
- 
++(/bin/sh /exts/exec.sh load_kmods && /bin/sh /exts/exec.sh on_boot_scripts && echo "Extensions processed") || Exit 99 "boot ext init exec failure"
+
  # insert Etron USB3.0 drivers
  
+ if [ $KERNEL_VCODE -ge "$(KernelVersionCode "3.10")" ]; then
+@@ -224,6 +229,7 @@
+ 		fi
+ fi
+ 
++(/bin/sh /exts/exec.sh load_kmods && /bin/sh /exts/exec.sh on_patches_scripts && echo "Extensions processed") || Exit 99 "patches ext init exec failure"
+ LoadBrmModules
+ 
+ ####################################################
